sudo: required

notifications:
  email: false

language: python
cache: pip

matrix:
  include:
  # mitogen_tests.sh
  - python: "2.7"
    env: MODE=mitogen DISTRO=debian
  #- python: "2.7"
    #env: MODE=mitogen DISTRO=centos
  - python: "3.6"
    env: MODE=mitogen DISTRO=debian

  # debops
  #- python: "2.7"
    #env: MODE=debops_common VER=2.4.3.0
  #- python: "2.7"
    #env: MODE=debops_common VER=2.5.1

  # ansible
  #- python: "2.7"
    #env: MODE=ansible VER=2.4.3.0 DISTRO=debian
  #- python: "2.7"
    #env: MODE=ansible VER=2.5.1 DISTRO=centos
  #- python: "2.7"
    #env: MODE=ansible VER=2.5.1 DISTRO=debian

install:
- pip install -r dev_requirements.txt

script:
- ${TRAVIS_BUILD_DIR}/.travis/${MODE}_tests.sh

services:
  - docker
